# Generated by Django 2.1 on 2018-08-23 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blogs.Topic_1')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
