# Generated by Django 2.1 on 2018-08-23 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0003_auto_20180823_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entries2',
            },
        ),
        migrations.CreateModel(
            name='Topic_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'topics2',
            },
        ),
        migrations.AddField(
            model_name='entry_2',
            name='topic_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blogs.Topic_2'),
        ),
    ]
