# Generated by Django 2.1 on 2018-08-23 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0004_auto_20180823_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entries3',
            },
        ),
        migrations.CreateModel(
            name='Entry_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entries4',
            },
        ),
        migrations.CreateModel(
            name='Topic_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'topics3',
            },
        ),
        migrations.CreateModel(
            name='Topic_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'topics4',
            },
        ),
        migrations.AddField(
            model_name='entry_4',
            name='topic_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blogs.Topic_4'),
        ),
        migrations.AddField(
            model_name='entry_3',
            name='topic_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blogs.Topic_3'),
        ),
    ]
